/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/display_settings`; params?: Router.UnknownInputParams; } | { pathname: `/font_settings`; params?: Router.UnknownInputParams; } | { pathname: `/hikaye`; params?: Router.UnknownInputParams; } | { pathname: `/notification_settings`; params?: Router.UnknownInputParams; } | { pathname: `/sure`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ayarlar` | `/ayarlar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/MuminAIDropdown`; params?: Router.UnknownInputParams; } | { pathname: `/components/SparkleIcon`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/sure-detail/[sure_id]`, params: Router.UnknownInputParams & { sure_id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/display_settings`; params?: Router.UnknownOutputParams; } | { pathname: `/font_settings`; params?: Router.UnknownOutputParams; } | { pathname: `/hikaye`; params?: Router.UnknownOutputParams; } | { pathname: `/notification_settings`; params?: Router.UnknownOutputParams; } | { pathname: `/sure`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ayarlar` | `/ayarlar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/components/MuminAIDropdown`; params?: Router.UnknownOutputParams; } | { pathname: `/components/SparkleIcon`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/sure-detail/[sure_id]`, params: Router.UnknownOutputParams & { sure_id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/display_settings${`?${string}` | `#${string}` | ''}` | `/font_settings${`?${string}` | `#${string}` | ''}` | `/hikaye${`?${string}` | `#${string}` | ''}` | `/notification_settings${`?${string}` | `#${string}` | ''}` | `/sure${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ayarlar${`?${string}` | `#${string}` | ''}` | `/ayarlar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/components/MuminAIDropdown${`?${string}` | `#${string}` | ''}` | `/components/SparkleIcon${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/display_settings`; params?: Router.UnknownInputParams; } | { pathname: `/font_settings`; params?: Router.UnknownInputParams; } | { pathname: `/hikaye`; params?: Router.UnknownInputParams; } | { pathname: `/notification_settings`; params?: Router.UnknownInputParams; } | { pathname: `/sure`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ayarlar` | `/ayarlar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/MuminAIDropdown`; params?: Router.UnknownInputParams; } | { pathname: `/components/SparkleIcon`; params?: Router.UnknownInputParams; } | `/+not-found` | `/sure-detail/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/sure-detail/[sure_id]`, params: Router.UnknownInputParams & { sure_id: string | number; } };
    }
  }
}
